// Formation Presets from editorStore.ts (lines 241-1172)
export const FORMATION_PRESETS: Record<string, { name: string; players: Array<{ role: string; label: string; x: number; y: number; appearance?: { shape?: PlayerShape; fill?: string; stroke?: string; showLabel?: boolean; radius?: number } }> }> = {
  iFormation: {
    name: 'I Formation',
    players: [
      // Ball at center
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      // O-Line
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'TE', x: 0.38, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.1, y: -0.03 },
      // Backfield (under center)
      { role: 'QB', label: 'QB', x: 0.5, y: -0.08 },
      { role: 'FB', label: 'FB', x: 0.5, y: -0.13 },
      { role: 'RB', label: 'RB', x: 0.5, y: -0.19 },
      { role: 'WR', label: 'Z', x: 0.9, y: -0.03 },
    ],
  },
  shotgun: {
    name: 'Shotgun',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'TE', x: 0.62, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.1, y: -0.03 },
      { role: 'WR', label: 'H', x: 0.2, y: -0.05 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.15 },
      { role: 'RB', label: 'RB', x: 0.42, y: -0.15 },
      { role: 'WR', label: 'Z', x: 0.9, y: -0.03 },
    ],
  },
  spread: {
    name: 'Spread 2x2',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'H', x: 0.15, y: -0.05 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.15 },
      { role: 'RB', label: 'RB', x: 0.58, y: -0.15 },
      { role: 'WR', label: 'Y', x: 0.85, y: -0.03 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
    ],
  },
  trips: {
    name: 'Trips Right',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.15 },
      { role: 'RB', label: 'RB', x: 0.42, y: -0.15 },
      { role: 'WR', label: 'H', x: 0.72, y: -0.05 },
      { role: 'WR', label: 'Y', x: 0.82, y: -0.03 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
    ],
  },
  bunch: {
    name: 'Bunch Right',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.15 },
      { role: 'RB', label: 'RB', x: 0.42, y: -0.15 },
      { role: 'TE', label: 'Y', x: 0.75, y: -0.03 },
      { role: 'WR', label: 'H', x: 0.78, y: -0.08 },
      { role: 'WR', label: 'Z', x: 0.82, y: -0.03 },
    ],
  },
  singleBack: {
    name: 'Single Back',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'Y', x: 0.35, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.1, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.08 },
      { role: 'RB', label: 'RB', x: 0.5, y: -0.15 },
      { role: 'WR', label: 'H', x: 0.65, y: -0.05 },
      { role: 'WR', label: 'Z', x: 0.9, y: -0.03 },
    ],
  },
  proSet: {
    name: 'Pro Set',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'Y', x: 0.35, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.1, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.08 },
      { role: 'RB', label: 'RB', x: 0.42, y: -0.13 },
      { role: 'FB', label: 'FB', x: 0.58, y: -0.13 },
      { role: 'WR', label: 'Z', x: 0.9, y: -0.03 },
    ],
  },
  pistol: {
    name: 'Pistol',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.1, y: -0.03 },
      { role: 'WR', label: 'H', x: 0.2, y: -0.05 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.10 },
      { role: 'RB', label: 'RB', x: 0.5, y: -0.18 },
      { role: 'WR', label: 'Y', x: 0.8, y: -0.03 },
      { role: 'WR', label: 'Z', x: 0.9, y: -0.03 },
    ],
  },
  twins: {
    name: 'Twins Right',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'Y', x: 0.62, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.1, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.15 },
      { role: 'RB', label: 'RB', x: 0.42, y: -0.15 },
      { role: 'WR', label: 'H', x: 0.78, y: -0.05 },
      { role: 'WR', label: 'Z', x: 0.9, y: -0.03 },
    ],
  },
  wingT: {
    name: 'Wing-T',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'TE', x: 0.62, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.1, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.08 },
      { role: 'FB', label: 'FB', x: 0.5, y: -0.13 },
      { role: 'RB', label: 'WB', x: 0.70, y: -0.07 },
      { role: 'RB', label: 'TB', x: 0.42, y: -0.13 },
    ],
  },
  ace: {
    name: 'Ace (12 Personnel)',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'Y', x: 0.35, y: -0.03 },
      { role: 'TE', label: 'U', x: 0.62, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.1, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.08 },
      { role: 'RB', label: 'RB', x: 0.5, y: -0.15 },
      { role: 'WR', label: 'Z', x: 0.9, y: -0.03 },
    ],
  },
  emptySet: {
    name: 'Empty Set',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'H', x: 0.2, y: -0.05 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.15 },
      { role: 'TE', label: 'Y', x: 0.62, y: -0.03 },
      { role: 'WR', label: 'F', x: 0.85, y: -0.03 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
    ],
  },
  goalLine: {
    name: 'Goal Line',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'Y', x: 0.35, y: -0.03 },
      { role: 'TE', label: 'U', x: 0.62, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.08 },
      { role: 'FB', label: 'FB', x: 0.5, y: -0.11 },
      { role: 'RB', label: 'RB', x: 0.5, y: -0.17 },
      { role: 'WR', label: 'X', x: 0.1, y: -0.03 },
    ],
  },
  slot: {
    name: 'Slot Right',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'Y', x: 0.62, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.1, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.15 },
      { role: 'RB', label: 'RB', x: 0.42, y: -0.15 },
      { role: 'WR', label: 'H', x: 0.78, y: -0.05 },
      { role: 'WR', label: 'Z', x: 0.9, y: -0.03 },
    ],
  },

  // ===== SPREAD/AIR RAID FORMATIONS =====
  tripsLeft: {
    name: 'Trips Left',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'H', x: 0.15, y: -0.05 },
      { role: 'WR', label: 'Y', x: 0.25, y: -0.03 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.15 },
      { role: 'RB', label: 'RB', x: 0.58, y: -0.15 },
    ],
  },
  bunchLeft: {
    name: 'Bunch Left',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.95, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.15 },
      { role: 'RB', label: 'RB', x: 0.58, y: -0.15 },
      { role: 'TE', label: 'Y', x: 0.25, y: -0.03 },
      { role: 'WR', label: 'H', x: 0.22, y: -0.08 },
      { role: 'WR', label: 'Z', x: 0.18, y: -0.03 },
    ],
  },
  twinsLeft: {
    name: 'Twins Left',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'Y', x: 0.35, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'H', x: 0.15, y: -0.05 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.15 },
      { role: 'RB', label: 'RB', x: 0.58, y: -0.15 },
    ],
  },
  emptyTrips: {
    name: 'Empty Trips',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'H', x: 0.15, y: -0.05 },
      { role: 'WR', label: 'Y', x: 0.25, y: -0.03 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'WR', label: 'F', x: 0.85, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.15 },
    ],
  },
  quadsRight: {
    name: 'Quads Right',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'WR', label: 'H', x: 0.85, y: -0.05 },
      { role: 'WR', label: 'Y', x: 0.75, y: -0.03 },
      { role: 'WR', label: 'F', x: 0.70, y: -0.07 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.15 },
    ],
  },
  quadsLeft: {
    name: 'Quads Left',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'H', x: 0.15, y: -0.05 },
      { role: 'WR', label: 'Y', x: 0.25, y: -0.03 },
      { role: 'WR', label: 'F', x: 0.30, y: -0.07 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.15 },
    ],
  },
  stackRight: {
    name: 'Stack Right',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'Z', x: 0.85, y: -0.03 },
      { role: 'WR', label: 'H', x: 0.85, y: -0.09 },
      { role: 'TE', label: 'TE', x: 0.62, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.15 },
      { role: 'RB', label: 'RB', x: 0.42, y: -0.15 },
    ],
  },
  stackLeft: {
    name: 'Stack Left',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.15, y: -0.03 },
      { role: 'WR', label: 'H', x: 0.15, y: -0.09 },
      { role: 'TE', label: 'TE', x: 0.38, y: -0.03 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.15 },
      { role: 'RB', label: 'RB', x: 0.58, y: -0.15 },
    ],
  },
  treyRight: {
    name: 'Trey Right',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'TE', x: 0.62, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'H', x: 0.75, y: -0.05 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.15 },
      { role: 'RB', label: 'RB', x: 0.42, y: -0.15 },
    ],
  },
  treyLeft: {
    name: 'Trey Left',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'TE', x: 0.38, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'H', x: 0.25, y: -0.05 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.15 },
      { role: 'RB', label: 'RB', x: 0.58, y: -0.15 },
    ],
  },
  spreadTight: {
    name: 'Spread Tight',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'H', x: 0.20, y: -0.05 },
      { role: 'WR', label: 'Y', x: 0.80, y: -0.03 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'TE', label: 'TE', x: 0.62, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.12 },
    ],
  },
  slotLeft: {
    name: 'Slot Left',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'TE', x: 0.38, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'H', x: 0.20, y: -0.05 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.15 },
      { role: 'RB', label: 'RB', x: 0.58, y: -0.15 },
    ],
  },

  // ===== PRO STYLE/WEST COAST FORMATIONS =====
  aceTwinsRight: {
    name: 'Ace Twins Right',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'Y', x: 0.35, y: -0.03 },
      { role: 'TE', label: 'U', x: 0.62, y: -0.03 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'WR', label: 'H', x: 0.85, y: -0.05 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.08 },
      { role: 'RB', label: 'RB', x: 0.5, y: -0.15 },
    ],
  },
  aceTwinsLeft: {
    name: 'Ace Twins Left',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'Y', x: 0.35, y: -0.03 },
      { role: 'TE', label: 'U', x: 0.62, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'H', x: 0.15, y: -0.05 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.08 },
      { role: 'RB', label: 'RB', x: 0.5, y: -0.15 },
    ],
  },
  splitBacks: {
    name: 'Split Backs',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'TE', x: 0.62, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.08 },
      { role: 'RB', label: 'RB', x: 0.42, y: -0.13 },
      { role: 'FB', label: 'FB', x: 0.58, y: -0.13 },
    ],
  },
  doubleTightRight: {
    name: 'Double Tight Right',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'Y', x: 0.62, y: -0.03 },
      { role: 'TE', label: 'U', x: 0.70, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.08 },
      { role: 'RB', label: 'RB', x: 0.5, y: -0.15 },
    ],
  },
  doubleTightLeft: {
    name: 'Double Tight Left',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'Y', x: 0.36, y: -0.03 },
      { role: 'TE', label: 'U', x: 0.30, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.08 },
      { role: 'RB', label: 'RB', x: 0.5, y: -0.15 },
    ],
  },
  heavy: {
    name: 'Heavy',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'Y', x: 0.35, y: -0.03 },
      { role: 'TE', label: 'U', x: 0.62, y: -0.03 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.08 },
      { role: 'FB', label: 'FB', x: 0.5, y: -0.13 },
      { role: 'RB', label: 'RB', x: 0.5, y: -0.19 },
    ],
  },
  jumbo: {
    name: 'Jumbo',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'Y', x: 0.35, y: -0.03 },
      { role: 'TE', label: 'U', x: 0.62, y: -0.03 },
      { role: 'TE', label: 'F', x: 0.70, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.08 },
      { role: 'FB', label: 'FB', x: 0.5, y: -0.13 },
      { role: 'RB', label: 'RB', x: 0.5, y: -0.19 },
    ],
  },
  unbalancedRight: {
    name: 'Unbalanced Right',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.45, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.40, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.50, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.35, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.55, y: -0.03 },
      { role: 'TE', label: 'Y', x: 0.59, y: -0.03 },
      { role: 'TE', label: 'U', x: 0.62, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.45, y: -0.08 },
      { role: 'RB', label: 'RB', x: 0.45, y: -0.15 },
    ],
  },
  unbalancedLeft: {
    name: 'Unbalanced Left',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.55, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.50, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.60, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.45, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.62, y: -0.03 },
      { role: 'TE', label: 'Y', x: 0.41, y: -0.03 },
      { role: 'TE', label: 'U', x: 0.35, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.55, y: -0.08 },
      { role: 'RB', label: 'RB', x: 0.55, y: -0.15 },
    ],
  },
  near: {
    name: 'Near',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'TE', x: 0.62, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.08 },
      { role: 'FB', label: 'FB', x: 0.55, y: -0.12 },
      { role: 'RB', label: 'RB', x: 0.5, y: -0.18 },
    ],
  },

  // ===== POWER RUN/SMASHMOUTH FORMATIONS =====
  far: {
    name: 'Far',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'TE', x: 0.62, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.08 },
      { role: 'FB', label: 'FB', x: 0.45, y: -0.12 },
      { role: 'RB', label: 'RB', x: 0.5, y: -0.18 },
    ],
  },
  fullHouse: {
    name: 'Full House',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'TE', x: 0.62, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.08 },
      { role: 'FB', label: 'FB', x: 0.5, y: -0.13 },
      { role: 'RB', label: 'HB1', x: 0.42, y: -0.18 },
      { role: 'RB', label: 'HB2', x: 0.58, y: -0.18 },
    ],
  },
  marylandI: {
    name: 'Maryland I',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'TE', x: 0.62, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.08 },
      { role: 'FB', label: 'FB', x: 0.55, y: -0.10 },
      { role: 'RB', label: 'RB', x: 0.5, y: -0.18 },
    ],
  },
  powerI: {
    name: 'Power I',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'Y', x: 0.35, y: -0.03 },
      { role: 'TE', label: 'U', x: 0.62, y: -0.03 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.08 },
      { role: 'FB', label: 'FB', x: 0.5, y: -0.13 },
      { role: 'RB', label: 'RB', x: 0.5, y: -0.19 },
    ],
  },
  wingRight: {
    name: 'Wing Right',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'TE', x: 0.62, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.08 },
      { role: 'FB', label: 'FB', x: 0.70, y: -0.08 },
      { role: 'RB', label: 'RB', x: 0.5, y: -0.15 },
    ],
  },
  wingLeft: {
    name: 'Wing Left',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'TE', x: 0.38, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.08 },
      { role: 'FB', label: 'FB', x: 0.30, y: -0.08 },
      { role: 'RB', label: 'RB', x: 0.5, y: -0.15 },
    ],
  },
  big: {
    name: 'Big',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'Y', x: 0.36, y: -0.03 },
      { role: 'TE', label: 'U', x: 0.62, y: -0.03 },
      { role: 'TE', label: 'F', x: 0.30, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.08 },
      { role: 'FB', label: 'FB', x: 0.5, y: -0.12 },
      { role: 'RB', label: 'RB', x: 0.5, y: -0.17 },
    ],
  },
  tightBunchRight: {
    name: 'Tight Bunch Right',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'Y', x: 0.62, y: -0.03 },
      { role: 'WR', label: 'H', x: 0.72, y: -0.06 },
      { role: 'WR', label: 'Z', x: 0.72, y: -0.12 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.08 },
      { role: 'RB', label: 'RB', x: 0.5, y: -0.15 },
    ],
  },
  tightBunchLeft: {
    name: 'Tight Bunch Left',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'Y', x: 0.35, y: -0.03 },
      { role: 'WR', label: 'H', x: 0.28, y: -0.06 },
      { role: 'WR', label: 'X', x: 0.28, y: -0.12 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.08 },
      { role: 'RB', label: 'RB', x: 0.5, y: -0.15 },
    ],
  },
  tFormation: {
    name: 'T Formation',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'LE', x: 0.35, y: -0.03 },
      { role: 'TE', label: 'RE', x: 0.62, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.08 },
      { role: 'RB', label: 'LH', x: 0.42, y: -0.12 },
      { role: 'FB', label: 'FB', x: 0.5, y: -0.12 },
      { role: 'RB', label: 'RH', x: 0.58, y: -0.12 },
    ],
  },

  // ===== OPTION/TRIPLE OPTION FORMATIONS =====
  wishbone: {
    name: 'Wishbone',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'TE', x: 0.62, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.08 },
      { role: 'FB', label: 'FB', x: 0.5, y: -0.12 },
      { role: 'RB', label: 'LH', x: 0.42, y: -0.18 },
      { role: 'RB', label: 'RH', x: 0.58, y: -0.18 },
    ],
  },
  flexbone: {
    name: 'Flexbone',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'TE', x: 0.62, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.08 },
      { role: 'RB', label: 'A', x: 0.32, y: -0.08 },
      { role: 'RB', label: 'B', x: 0.5, y: -0.15 },
    ],
  },
  veer: {
    name: 'Veer',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'TE', x: 0.62, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.08 },
      { role: 'RB', label: 'HB', x: 0.42, y: -0.10 },
      { role: 'RB', label: 'FB', x: 0.58, y: -0.10 },
    ],
  },
  wildcat: {
    name: 'Wildcat',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'TE', x: 0.62, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'RB', label: 'RB', x: 0.5, y: -0.12 },
      { role: 'QB', label: 'QB', x: 0.35, y: -0.08 },
      { role: 'RB', label: 'HB', x: 0.58, y: -0.15 },
    ],
  },
  speedOption: {
    name: 'Speed Option',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'TE', x: 0.62, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'H', x: 0.15, y: -0.05 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.15 },
      { role: 'RB', label: 'RB', x: 0.42, y: -0.15 },
    ],
  },
  midlineOption: {
    name: 'Midline',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'TE', x: 0.62, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.08 },
      { role: 'FB', label: 'FB', x: 0.5, y: -0.12 },
      { role: 'RB', label: 'RB', x: 0.58, y: -0.15 },
    ],
  },
  loadOption: {
    name: 'Load Option',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'TE', x: 0.62, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'H', x: 0.70, y: -0.07 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.15 },
      { role: 'RB', label: 'RB', x: 0.42, y: -0.15 },
    ],
  },
  tripleRight: {
    name: 'Triple Right',
    players: [
      { role: 'BALL', label: '🏈', x: 0.5, y: 0, appearance: { shape: 'football', fill: '#8B4513', stroke: '#ffffff', showLabel: false, radius: 10 } },
      { role: 'C', label: 'C', x: 0.5, y: -0.03 },
      { role: 'LG', label: 'LG', x: 0.46, y: -0.03 },
      { role: 'RG', label: 'RG', x: 0.54, y: -0.03 },
      { role: 'LT', label: 'LT', x: 0.42, y: -0.03 },
      { role: 'RT', label: 'RT', x: 0.58, y: -0.03 },
      { role: 'TE', label: 'TE', x: 0.62, y: -0.03 },
      { role: 'WR', label: 'X', x: 0.05, y: -0.03 },
      { role: 'WR', label: 'Z', x: 0.95, y: -0.03 },
      { role: 'QB', label: 'QB', x: 0.5, y: -0.08 },
      { role: 'RB', label: 'A', x: 0.68, y: -0.08 },
      { role: 'RB', label: 'B', x: 0.5, y: -0.15 },
    ],
  },
};
